version: '3.1'

services:
 app:
  build: ./
  restart: unless-stopped
  ports:
   - 8585:80
   - 4443:443
  environment:
   DB_HOST: db
   MYSQL_ROOT_PASSWORD: your_password
  volumes:
   - ./data/tuleap-data:/data
  depends_on:
   - db
   
 db:
  image: mysql:5.6
  restart: unless-stopped
  volumes:
   - ./data/db-data:/var/lib/mysql
   - ./data/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
  environment:
   MYSQL_ROOT_PASSWORD: your_password
