@startuml tuleap_close_network

cloud internet {
    artifact Tuleap [
    <b>Tuleap</b>
    ---
    https://ci.tuleap.net/yum/tuleap/rhel/6/dev/
    ]

    artifact Centos [
    <b>centos</b>
    ---
    http://mirror.centos.org/centos/
    ]


    artifact Epel [
    <b>epel</b>
    ---
    http://mirror.linux-ia64.org/epel/6/
    ]


    artifact Remirepo [
    <b>remirepo</b>
    ---
    http://rpms.remirepo.net/enterprise/6/safe/
    ]
}

component nexus {
    artifact proxyTuleap [
    <b>Tuleap proxy</b>
    ]

    artifact proxyCentos [
    <b>Centos proxy</b>
    ]

    artifact proxyEpel [
    <b>Epel proxy</b>
    ]

    artifact proxyRemirepo [
    <b>Remirepo proxy</b>
    ]
}

node server {
    component docker [
        docker
    ]
    component dockercompose [
        docker-compose
    ]
    folder docker-tuleap {
        file Dockerfile 
        file dockercomposeyml [
            docker-compose.yml
        ]
        folder repos {
            file epelrepo [
                epel.repo
            ]
            file remisafe [
                remi-safe.repo
            ]
            file CentOSBaserepo [
                CentOS-Base.repo
            ]
            file Tuleaprepo [
                Tuleap.repo
            ]
        }

        epelrepo <-- Dockerfile
        remisafe <-- Dockerfile
        CentOSBaserepo <-- Dockerfile
        Tuleaprepo <-- Dockerfile

        Dockerfile <-- dockercomposeyml
    }
}

Tuleap -(0)- proxyTuleap
Centos -(0)- proxyCentos
Epel -(0)- proxyEpel
Remirepo -(0)- proxyRemirepo

proxyEpel <-- epelrepo
proxyRemirepo <-- remisafe
proxyCentos <-- CentOSBaserepo
proxyTuleap <-- Tuleaprepo









@enduml